def MAC_areas_regions(df):
  df.loc[df["AREA"] == "29-30", "AREA"] = "29/30"
  df.loc[df["AREA"] == "prost", "AREA"] = "pro.st."
  df.loc[df["AREA"] == "tea-m a", "AREA"] = "tea/ma"
  df.loc[df["AREA"] == "tea-m p", "AREA"] = "tea/mp"
  df.loc[df["AREA"] == "th-tf", "AREA"] = "th/tf"
  df.loc[df["AREA"] == "9-46d", "AREA"] = "9/46d"
  df.loc[df["AREA"] == "9-46v", "AREA"] = "9/46v"
  df.loc[df["AREA"] == "opal", "AREA"] = "opai"
  df.loc[df["AREA"] == "t.pole", "AREA"] = "pole"
  df.loc[df["AREA"] == "parains", "AREA"] = "pi"
  df.loc[df["AREA"] == "insula", "AREA"] = "insula"
  df.loc[df["AREA"] == "aud. core", "AREA"] = "core"
  df.loc[df["AREA"] == "35-36", "AREA"] = "35/36"