name: Wheels
on:
  push:
    tags: ["v*.*.*"]   # build on version tags
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }   # needed for setuptools-scm
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install cibuildwheel
        run: pipx run --spec cibuildwheel==2.21.3 cibuildwheel --print-build-identifiers
      - name: Build wheels
        run: pipx run cibuildwheel --output-dir wheelhouse
      - name: Build sdist (once)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pipx run build --sdist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: |
            wheelhouse/*.whl
            dist/*.tar.gz

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { path: dist_all }
      - name: Flatten
        run: |
          mkdir dist && find dist_all -name "*.whl" -o -name "*.tar.gz" -exec cp {} dist/ \;
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
